const dataDummy = {
  simulationReport1: {
    pageTable: [
      {
        pageId: 0,
        pid: 1,
        loaded: "X",
        loadedT: "1s",
        mark: "",
        laddr: 0,
        daddr: 0,
        maddr: 0,
      },
      {
        pageId: 1,
        pid: 1,
        loaded: "X",
        loadedT: "1s",
        mark: "",
        laddr: 1,
        daddr: 0,
        maddr: 1,
      },
      {
        pageId: 2,
        pid: 1,
        loaded: "X",
        loadedT: "1s",
        mark: "",
        laddr: 2,
        daddr: 0,
        maddr: 2,
      },
      {
        pageId: 3,
        pid: 1,
        loaded: "X",
        loadedT: "1s",
        mark: "",
        laddr: 3,
        daddr: 0,
        maddr: 3,
      },
      {
        pageId: 4,
        pid: 1,
        loaded: "X",
        loadedT: "1s",
        mark: "",
        laddr: 4,
        daddr: 0,
        maddr: 4,
      },
      {
        pageId: 5,
        pid: 1,
        loaded: "X",
        loadedT: "1s",
        mark: "",
        laddr: 5,
        daddr: 0,
        maddr: 5,
      },
      {
        pageId: 6,
        pid: 1,
        loaded: "X",
        loadedT: "1s",
        mark: "",
        laddr: 6,
        daddr: 0,
        maddr: 6,
      },
      {
        pageId: 7,
        pid: 1,
        loaded: "X",
        loadedT: "1s",
        mark: "",
        laddr: 7,
        daddr: 0,
        maddr: 7,
      },
      {
        pageId: 8,
        pid: 1,
        loaded: "X",
        loadedT: "1s",
        mark: "",
        laddr: 8,
        daddr: 0,
        maddr: 8,
      },
      {
        pageId: 9,
        pid: 1,
        loaded: "X",
        loadedT: "1s",
        mark: "",
        laddr: 9,
        daddr: 0,
        maddr: 9,
      },
    ],
    simulationDuration: 10,
    totalProcesses: 1,
    realMemoryUsageInKb: 40,
    realMemoryUsagePercentage: 10,
    virtualMemoryUsageInKb: 0,
    virtualMemoryUsagePercentage: 0,
    internalFragmentation: 5215,
    trashingDuration: 0,
    trashingPercentage: 0,
    pagesLoadedInMemory: 10,
    pagesInVirtualMemory: 0,
  },
  simulationReport2: {
    pageTable: [
      {
        pageId: 0,
        pid: 1,
        loaded: "X",
        loadedT: "1s",
        mark: "",
        laddr: 0,
        daddr: 0,
        maddr: 0,
      },
      {
        pageId: 1,
        pid: 1,
        loaded: "X",
        loadedT: "1s",
        mark: "",
        laddr: 1,
        daddr: 0,
        maddr: 1,
      },
      {
        pageId: 2,
        pid: 1,
        loaded: "X",
        loadedT: "1s",
        mark: "",
        laddr: 2,
        daddr: 0,
        maddr: 2,
      },
      {
        pageId: 3,
        pid: 1,
        loaded: "X",
        loadedT: "1s",
        mark: "",
        laddr: 3,
        daddr: 0,
        maddr: 3,
      },
      {
        pageId: 4,
        pid: 1,
        loaded: "X",
        loadedT: "1s",
        mark: "",
        laddr: 4,
        daddr: 0,
        maddr: 4,
      },
      {
        pageId: 5,
        pid: 1,
        loaded: "X",
        loadedT: "1s",
        mark: "",
        laddr: 5,
        daddr: 0,
        maddr: 5,
      },
      {
        pageId: 6,
        pid: 1,
        loaded: "X",
        loadedT: "1s",
        mark: "",
        laddr: 6,
        daddr: 0,
        maddr: 6,
      },
      {
        pageId: 7,
        pid: 1,
        loaded: "X",
        loadedT: "1s",
        mark: "",
        laddr: 7,
        daddr: 0,
        maddr: 7,
      },
      {
        pageId: 8,
        pid: 7,
        loaded: "X",
        loadedT: "1s",
        mark: "",
        laddr: 8,
        daddr: 0,
        maddr: 8,
      },
      {
        pageId: 9,
        pid: 7,
        loaded: "X",
        loadedT: "1s",
        mark: "",
        laddr: 9,
        daddr: 0,
        maddr: 9,
      },
    ],
    simulationDuration: 10,
    totalProcesses: 1,
    realMemoryUsageInKb: 40,
    realMemoryUsagePercentage: 10,
    virtualMemoryUsageInKb: 0,
    virtualMemoryUsagePercentage: 0,
    internalFragmentation: 5215,
    trashingDuration: 0,
    trashingPercentage: 0,
    pagesLoadedInMemory: 10,
    pagesInVirtualMemory: 0,
  },
};

export default dataDummy;
